### ISSUE TITLE
nextSpecialBonus is redundant and wastes gas

### ISSUE THREAD

**Issue by dafky2000** [codemojo-dr/Alloy-ICO-Contracts#1]

**Comment by shoaib-dr** [comment]
`nextSpecialBonus` gets the next available bonus based on the timeline of the crowdsale. Removing this and using `getBonusSlab()` inside the `buyTokens` function will result in the 0 index of the bonus slab being executed & will send out wrong number of Alloys (+10%) allocated to the user

**Comment by shoaib-dr** [comment]
Additionally, both the functions are not redundant, they are intended for different operations at different points in time.

`getBonusSlab()` lets users to jump through each of the bonus slabs available so there is transparency. This will use **0 gas**

`nextSpecialBonus()` will let both the crowdsale contract & users to see which bonus slab is running and when it will end. This will use **0 gas**

**Comment by shoaib-dr** [comment]
You can however submit just the optimization patch for Line#54 either as a update or by raising a new issue and submitting a pull. As a side note, I would be recommended to remove the comment added in the code `// No need to verify slabIndex >= 0, function only accepts uint so is redundant` and move it to the commit message during

**Comment by dafky2000** [comment]
Wow, I clearly missed the difference between the two functions. And I will have to research how gas is used, I wrongly assumed every operation consumed gas. I will submit another pull request with the minor optimization.
