### ISSUE TITLE
Add keyword "constant" to the variables that do not change their values

### ISSUE THREAD

**Issue by pauliax** [codemojo-dr/Alloy-ICO-Contracts#3]
Reading from a const variable doesn't cost any gas so this would save you some money. For example, replace:
    
    string public name = 'ALLOY';
    string public symbol = 'ALLOY';
    uint public decimals = 18;
with 	
	
    string public constant name = 'ALLOY';
    string public constant symbol = 'ALLOY';
    uint public constant decimals = 18;

**Comment by shoaib-dr** [comment]
Has been added in the commit https://github.com/codemojo-dr/Alloy-ICO-Contracts/commit/e03b7e17f5cc4e002ee0961eb236ea31d6574e96
