### ISSUE TITLE
Consider marking functions with a specific access level

### ISSUE THREAD

**Issue by pauliax** [codemojo-dr/Alloy-ICO-Contracts#4]
For example, functions that aren't called internally, please mark with a keyword "external". Calling external function consumes less gas than public function. Also, functions that are only used internally, should be marked "internal". If you want, I can specify which modifier every function should have.

**Comment by shoaib-dr** [comment]
Woud appreciate if you can fork & do a mark up, it would be easier to do a pull & run some tests as well.

**Comment by shoaib-dr** [comment]
Patched as https://github.com/codemojo-dr/Alloy-ICO-Contracts/commit/e3e5da7b53f2103bd646f9df5086c8f9bd27edd1 & https://github.com/codemojo-dr/Alloy-ICO-Contracts/commit/132fa7f1adb81a746ed7adf81f443d90a3cded31
