### ISSUE TITLE
SafeMath.sol unused functions

### ISSUE THREAD

**Issue by pauliax** [codemojo-dr/Alloy-ICO-Contracts#6]
Consider removing these functions. They are not used, so there is no point in keeping it. It will cost less gas to deploy the contract.

		function max64(uint64 a, uint64 b) internal constant returns (uint64) {
		    return a >= b ? a : b;
		  }

		  function min64(uint64 a, uint64 b) internal constant returns (uint64) {
		    return a < b ? a : b;
		  }

		  function max256(uint256 a, uint256 b) internal constant returns (uint256) {
		    return a >= b ? a : b;
		  }

		  function min256(uint256 a, uint256 b) internal constant returns (uint256) {
		    return a < b ? a : b;
		  }

**Comment by shoaib-dr** [comment]
These are used in `VestedToken.sol`
