### ISSUE TITLE
Unused variable in function

### ISSUE THREAD

**Issue by pauliax** [codemojo-dr/Alloy-ICO-Contracts#7]
LimitedTransferToken.sol
Unused local variable "time": 
function transferableTokens(address holder, uint64 time) public constant returns (uint256) 
Consider removing it to save gas every time you call this function.

**Comment by shoaib-dr** [comment]
This is part of the logic which gets overriden by `VestedToken:102` which inherits `LimitedTransferToken`. As you can see, VestedToken uses the time  starting from the line  `if (grantIndex == 0) return super.transferableTokens(holder, time); // shortcut for holder without grants`
