### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by pauliax** [codemojo-dr/Alloy-ICO-Contracts#8]
Migrations.sol
import Ownable contract to Migrations contract, add inheritance:

            contract Migrations is Ownable
and then remove:

           address public owner;
            
           modifier restricted() {
                if (msg.sender == owner) _;
            }

            function Migrations() {
                owner = msg.sender;
            }

then, instead of marking function "restricted", mark it "onlyOwner".
This helps you to avoid code duplication.

**Comment by shoaib-dr** [comment]
Fixed https://github.com/codemojo-dr/Alloy-ICO-Contracts/commit/776ade7ecee8bfd6e4c1b393c6e15d5796956a8b
