### ISSUE TITLE
Method Approve is vulnerable

### ISSUE THREAD

**Issue by pauliax** [codemojo-dr/Alloy-ICO-Contracts#9]
Approve method is vulnerable to the issue described here: https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit#heading=h.m9fhqynw2xvt
	please consider adding this check at the beginning of the method: 
// To change the approve amount you first have to reduce the addresses`
//  allowance to zero by calling `approve(_spender, 0)` if it is not
//  already 0 to mitigate the race condition described here:
//  https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729 …

    require((_value == 0) || (allowed[msg.sender][_spender] == 0));

**Comment by shoaib-dr** [comment]
This was recently removed as a part of the patch to the OpenZeppelin framework  under the pretext that this violates the ERC20 standards. 

More details on https://github.com/OpenZeppelin/zeppelin-solidity/commit/83918cad4b9f5bea6dcb3c0c18f3295b2484c825
